version: '3'

services:
  netdata:
    image: netdata/netdata
    ports:
      - "1111:19999"

  jupyterlab:
    build: ./jupyter
    ports:
      - "8888:8888"
    volumes:
      - ./jupyter/notebooks:/home/jovyan/notebooks

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/html:/usr/share/nginx/html
    ports:
      - "80:80"
